// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopThreadRouteAuthority } from "./DesktopThreadRouteAuthority";
import type { DesktopThreadSelection } from "./DesktopThreadSelection";

export type DesktopThreadSelectionReadResponse = { selection: DesktopThreadSelection | null, authority: DesktopThreadRouteAuthority, reason: string | null, };
