// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopThreadRouteParams = { threadId: string,
/**
 * When true, the desktop host may focus/raise its window while routing.
 * Omission means false so clients can request quiet routing by default.
 */
focus?: boolean, };
